### ISSUE TITLE
COMIC FUZ Support

### ISSUE THREAD

**Issue by monesys** [xuzhengyi1995/Bookwalker_Downloader#2]
COMIC FUZ seems to use the same PUBLUS Web Viewer as BookWalker.
Would supporting it be acceptable?

and may I have your contact details?

Thank you.

**Comment by xuzhengyi1995** [comment]
Yes but I have seen that the COMIC FUZ use a old version of PUBLUS Web Viewer and the datas haven't been encrypted and the JavaScript code is very easy to understand(I have tried the free Manga but maybe there are some different in the paid Manga, I'm not sure. ).

So maybe it's possible to download it by using the way I have used in the **Renta_Downloader** and no need to use a browser.

I have sent you a friend request on Discord.

Thank you.

**Comment by xuzhengyi1995** [comment]
Now you can find it here [Comic-fuz-Downloader](https://github.com/xuzhengyi1995/Comic-fuz-Downloader).
Thank you.
