### ISSUE TITLE
能运用到中文版站点吗

### ISSUE THREAD

**Issue by xiongtutuyihao** [xuzhengyi1995/Bookwalker_Downloader#4]
请问这个脚本要改动哪些地方能在中文版站点使用啊

**Comment by xuzhengyi1995** [comment]
> 请问这个脚本要改动哪些地方能在中文版站点使用啊

您好，该脚本可以通用中文站点，目前正在修改添加Cookies部分以自动适配给出的链接为日文站点还是中文站点，还请稍等，大约30分钟内完成。

**Comment by xuzhengyi1995** [comment]
经过测试，已经可以正常运行，还请获取新版本后尝试，感谢您的关注。

![image](https://user-images.githubusercontent.com/29002064/79818074-7bf40700-83b9-11ea-9cbf-fd5da74e6c9e.png)

**Comment by xiongtutuyihao** [comment]
已经成功了！感谢！
