### ISSUE TITLE
漫画的原始分辨率怎么拿到？

### ISSUE THREAD

**Issue by ChikaFujiwara** [xuzhengyi1995/Bookwalker_Downloader#5]
我试了下分辨率调到多高下下来的图片分辨率就有多高，那如何才能知道原始分辨率呢

**Comment by xuzhengyi1995** [comment]
感谢您的提问，关于原始分辨率，您可以这样操作：
1. 打开漫画，按下`F12`调出`DevTools`。
2. 转到`Network`，并刷新该页面。
3. 当内容加载完毕，您可以在该页面找到左边带有齿轮标志⚙的请求。
4. 立即单击右键，选择`Copy`->`Copy link address`。
5. 粘贴到新的标签页并打开。
6. 这时您可以看到一副被打乱的图片，该图片的分辨率为该漫画的原始分辨率。

请参考下图：
![image](https://user-images.githubusercontent.com/29002064/80913827-297ff680-8d7a-11ea-917e-2bb3ade66bd3.png)

![image](https://user-images.githubusercontent.com/29002064/80913862-6d72fb80-8d7a-11ea-9a8b-e90218e1f8eb.png)

打开的图片如图二所示，您可以单击右键另存为图片到电脑查看其原始分辨率，也可以点击放大后，使用调试工具查看其分辨率。

谢谢！

**Comment by ChikaFujiwara** [comment]
非常感谢！
